package xyz.mrwood.study.spring.boot.mybatis.dao;

import java.util.List;
import xyz.mrwood.study.spring.boot.mybatis.model.CarlifeTestMoney;

public interface CarlifeTestMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_test_money
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_test_money
     *
     * @mbggenerated
     */
    int insert(CarlifeTestMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_test_money
     *
     * @mbggenerated
     */
    CarlifeTestMoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_test_money
     *
     * @mbggenerated
     */
    List<CarlifeTestMoney> selectAll();
}