package xyz.mrwood.study.spring.boot.mybatis.dao;

import java.util.List;
import xyz.mrwood.study.spring.boot.mybatis.model.ServiceOrder;

public interface ServiceOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_service_orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_service_orders
     *
     * @mbggenerated
     */
    int insert(ServiceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_service_orders
     *
     * @mbggenerated
     */
    ServiceOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carlife_service_orders
     *
     * @mbggenerated
     */
    List<ServiceOrder> selectAll();
}