package xyz.mrwood.study.spring.boot.mybatis.model;

import java.util.Date;

public class CarlifeTestMoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.car_number
     *
     * @mbggenerated
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.parking_id
     *
     * @mbggenerated
     */
    private String parkingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.car_charge_type
     *
     * @mbggenerated
     */
    private String carChargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.enterTime
     *
     * @mbggenerated
     */
    private Date entertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.equipment_order_id
     *
     * @mbggenerated
     */
    private String equipmentOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.freeTime
     *
     * @mbggenerated
     */
    private String freetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.parking_time
     *
     * @mbggenerated
     */
    private String parkingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carlife_test_money.time_limit
     *
     * @mbggenerated
     */
    private String timeLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.id
     *
     * @return the value of carlife_test_money.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.id
     *
     * @param id the value for carlife_test_money.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.car_number
     *
     * @return the value of carlife_test_money.car_number
     *
     * @mbggenerated
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.car_number
     *
     * @param carNumber the value for carlife_test_money.car_number
     *
     * @mbggenerated
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.parking_id
     *
     * @return the value of carlife_test_money.parking_id
     *
     * @mbggenerated
     */
    public String getParkingId() {
        return parkingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.parking_id
     *
     * @param parkingId the value for carlife_test_money.parking_id
     *
     * @mbggenerated
     */
    public void setParkingId(String parkingId) {
        this.parkingId = parkingId == null ? null : parkingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.money
     *
     * @return the value of carlife_test_money.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.money
     *
     * @param money the value for carlife_test_money.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.car_charge_type
     *
     * @return the value of carlife_test_money.car_charge_type
     *
     * @mbggenerated
     */
    public String getCarChargeType() {
        return carChargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.car_charge_type
     *
     * @param carChargeType the value for carlife_test_money.car_charge_type
     *
     * @mbggenerated
     */
    public void setCarChargeType(String carChargeType) {
        this.carChargeType = carChargeType == null ? null : carChargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.code
     *
     * @return the value of carlife_test_money.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.code
     *
     * @param code the value for carlife_test_money.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.enterTime
     *
     * @return the value of carlife_test_money.enterTime
     *
     * @mbggenerated
     */
    public Date getEntertime() {
        return entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.enterTime
     *
     * @param entertime the value for carlife_test_money.enterTime
     *
     * @mbggenerated
     */
    public void setEntertime(Date entertime) {
        this.entertime = entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.equipment_order_id
     *
     * @return the value of carlife_test_money.equipment_order_id
     *
     * @mbggenerated
     */
    public String getEquipmentOrderId() {
        return equipmentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.equipment_order_id
     *
     * @param equipmentOrderId the value for carlife_test_money.equipment_order_id
     *
     * @mbggenerated
     */
    public void setEquipmentOrderId(String equipmentOrderId) {
        this.equipmentOrderId = equipmentOrderId == null ? null : equipmentOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.freeTime
     *
     * @return the value of carlife_test_money.freeTime
     *
     * @mbggenerated
     */
    public String getFreetime() {
        return freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.freeTime
     *
     * @param freetime the value for carlife_test_money.freeTime
     *
     * @mbggenerated
     */
    public void setFreetime(String freetime) {
        this.freetime = freetime == null ? null : freetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.msg
     *
     * @return the value of carlife_test_money.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.msg
     *
     * @param msg the value for carlife_test_money.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.parking_time
     *
     * @return the value of carlife_test_money.parking_time
     *
     * @mbggenerated
     */
    public String getParkingTime() {
        return parkingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.parking_time
     *
     * @param parkingTime the value for carlife_test_money.parking_time
     *
     * @mbggenerated
     */
    public void setParkingTime(String parkingTime) {
        this.parkingTime = parkingTime == null ? null : parkingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.status
     *
     * @return the value of carlife_test_money.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.status
     *
     * @param status the value for carlife_test_money.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carlife_test_money.time_limit
     *
     * @return the value of carlife_test_money.time_limit
     *
     * @mbggenerated
     */
    public String getTimeLimit() {
        return timeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carlife_test_money.time_limit
     *
     * @param timeLimit the value for carlife_test_money.time_limit
     *
     * @mbggenerated
     */
    public void setTimeLimit(String timeLimit) {
        this.timeLimit = timeLimit == null ? null : timeLimit.trim();
    }
}